select distinct
V1.N_MOIS_DONN
,V1.N_AN_DONNE
,V1.V_IDENT_PRJ
,V1.V_NOM_PRJ
,V1.CONCAT_ACT_PRJ
,V1.V_PROC_PRJ_2
,V1.V_ABD_REJ
,V1.C_TYPE_PROG
,V1.L_DEST_REPORT
,V1.D_DEPOT_DOSS_INNO
,V1.D_ENG
,V1.D_ENG_REV
,V1.D_SIGNATURE_CONTRAT
,V1.D_DEB_PRJ
,V1.D_FIN_PRJ
,V2.V_RESUME_PRJ
,V2.C_LOC_PRJ
,V2.L_THEM_PRJ
,V2.V_POT_VISIT
,V2.V_APPR_ETAT_PRJ
--,V1.C_SS_FDS
from
(
    select
        N_MOIS_DONN,
        N_AN_DONNE,
        V_IDENT_PRJ,
        V_NOM_PRJ,
        case when I_TYPE_PROG_INNO = 'PUI' then 'PUIAAP PUI' else concat(I_TYPE_PROG_INNO,V_PROC_PRJ) end as concat_act_proc,
        case when I_TYPE_PROG_INNO = 'PUI' then 'AAP PUI' else V_PROC_PRJ end as V_PROC_PRJ_2, 
        V_ABD_REJ,
        C_TYPE_PROG,
        L_DEST_REPORT,
        MIN(D_DEPOT_DOSS_INNO) D_DEPOT_DOSS_INNO,
        MIN(D_ENG) D_ENG,
        MAX(D_ENG_REV) D_ENG_REV,
        MIN(D_SIGNATURE_CONTRAT) D_SIGNATURE_CONTRAT,
        MIN(D_DEB_PRJ) D_DEB_PRJ,
        MAX(D_FIN_PRJ) D_FIN_PRJ
--, C_SS_FDS
    from
    (
        select distinct
            DBM01.DEPR_DETAIL_PROJET.N_MOIS_DONN,
            DBM01.DEPR_DETAIL_PROJET.N_AN_DONNE,
            DBM01.DEPR_DETAIL_PROJET.V_IDENT_PRJ,
            DBM01.DEPR_DETAIL_PROJET.V_NOM_PRJ,
            CASE WHEN C_TYPE_PROG = 'MONOPARTENAIRE' THEN
                CASE WHEN DBM01.DEPR_DETAIL_PROJET.I_TYPE_PROG_INNO in('ATF Régional', 'PROJ INNO PIA3 REGIO', 'French Tech Tremplin', 'FNI') then
                DBM01.DEPR_DETAIL_PROJET.V_PROC_PRJ
                ELSE DBM01.DEPR_DETAIL_PROJET.I_TYPE_PROG_INNO || '-' || DBM01.DEPR_DETAIL_PROJET.V_PROC_PRJ
                END
            ELSE V_PROC_PRJ
            END V_PROC_PRJ,
            COALESCE(DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ,'N') V_ABD_REJ, 
            DBM01.DEPR_DETAIL_PROJET.D_DEPOT_DOSS_INNO D_DEPOT_DOSS_INNO,
            CASE WHEN DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ is null THEN DBM01.DEPR_DETAIL_PROJET.D_ENG ELSE NULL END D_ENG,
            CASE WHEN DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ is null THEN DBM01.DEPR_DETAIL_PROJET.D_ENG_REV ELSE NULL END D_ENG_REV,
            CASE WHEN DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ is null THEN DBM01.DEPR_DETAIL_PROJET.D_SIGNATURE_CONTRAT ELSE NULL END D_SIGNATURE_CONTRAT,
            CASE WHEN DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ is null THEN DBM01.DEPR_DETAIL_PROJET.D_DEB_PRJ ELSE NULL END D_DEB_PRJ,
            CASE WHEN DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ is null THEN DBM01.DEPR_DETAIL_PROJET.D_FIN_PRJ ELSE NULL END D_FIN_PRJ,
            DBM01.DEPR_DETAIL_PROJET.C_TYPE_PROG,
            DBM01.DEPR_DETAIL_PROJET.C_PARTE_REPORT,
            DBM01.DEPR_DETAIL_PROJET.L_DEST_REPORT,
            DBM01.DEPR_DETAIL_PROJET.I_TYPE_PROG_INNO
            , DBM01.DEPR_DETAIL_PROJET.C_SS_FDS
        from DBM01.DEPR_DETAIL_PROJET
        where (V_PROC_PRJ is not null OR I_TYPE_PROG_INNO = 'PUI')
        and C_SS_FDS  NOT LIKE '%813%'
    )
    group by
    N_MOIS_DONN,
    N_AN_DONNE,
    V_IDENT_PRJ,
    V_NOM_PRJ,
    V_PROC_PRJ,
    V_ABD_REJ,
    C_TYPE_PROG,
    L_DEST_REPORT,
    I_TYPE_PROG_INNO
    --,C_SS_FDS
) V1
left outer join (
    select distinct
        DBM01.DEPR_DETAIL_PROJET.N_MOIS_DONN,
        DBM01.DEPR_DETAIL_PROJET.N_AN_DONNE,
        DBM01.DEPR_DETAIL_PROJET.V_IDENT_PRJ,
        FIRST_VALUE (DBM01.DEPR_DETAIL_PROJET.V_RESUME_PRJ) OVER (PARTITION BY DBM01.DEPR_DETAIL_PROJET.V_IDENT_PRJ, DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ ORDER BY C_SDC_CNTN) V_RESUME_PRJ,
        FIRST_VALUE(DBM01.DEPR_DETAIL_PROJET.C_LOC_PRJ) OVER (PARTITION BY DBM01.DEPR_DETAIL_PROJET.V_IDENT_PRJ, DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ ORDER BY C_SDC_CNTN, B_DOSS_REFER_COLLAB desc, C_STT_CDF desc) C_LOC_PRJ,
        CASE WHEN I_TYPE_PROG_INNO = 'SIA' THEN 'Multisectoriel; Deep Tech; Start Up'
ELSE ''
END L_THEM_PRJ,
        '' V_POT_VISIT,
        '' V_APPR_ETAT_PRJ
    from DBM01.DEPR_DETAIL_PROJET
    where C_SS_FDS  NOT LIKE '%813%'
) V2 on V1.N_MOIS_DONN = V2.N_MOIS_DONN and V1.N_AN_DONNE = V2.N_AN_DONNE and V1.V_IDENT_PRJ = V2.V_IDENT_PRJ
left outer join (
    select distinct
        DBM01.DEPR_DETAIL_PROJET.N_MOIS_DONN,
        DBM01.DEPR_DETAIL_PROJET.N_AN_DONNE,
        DBM01.DEPR_DETAIL_PROJET.V_IDENT_PRJ
    from DBM01.DEPR_DETAIL_PROJET
    where DBM01.DEPR_DETAIL_PROJET.V_ABD_REJ is null
    and C_SS_FDS  NOT LIKE '%813%'
    ) V3 on V1.N_MOIS_DONN = V3.N_MOIS_DONN and V1.N_AN_DONNE = V3.N_AN_DONNE and V1.V_IDENT_PRJ = V3.V_IDENT_PRJ and V1.V_ABD_REJ != 'N'
WHERE V3.V_IDENT_PRJ is null
and
  (
   V1.N_MOIS_DONN  IN  @dpvalue('N', DP6.DO1)
   AND
   V1.N_AN_DONNE  IN  @dpvalue('N', DP6.DO2)
   AND
   V1.L_DEST_REPORT  in  @prompt('Entrer Libelle du destinataire du reporting','A','Données referentiel projet\Libelle du destinataire du reporting',Multi,Free,Persistent,,User:0)
 -- and  V1.C_SS_FDS  NOT LIKE '%813%'
  )
with ur